name: 'Update AndroidManifest.xml Action'
description: 'Update the AndroidManifest.xml file to dynamically version or name projects built for Android.'
author: 'zockicookie'
inputs:
  android-manifest-path:
    description: 'Relative path for the AndroidManifest.xml file.'
    required: true
  package-name:
    description: 'Package name'
    required: true
  version-code:
    description: 'Version code value'
    required: true
  version-name:
    description: 'Version name'
    required: true
  print-file:
    description: 'Output the AndroidManifest.xml file in console'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'file'
  color: 'blue'
